# Generated by Django 5.2.6 on 2026-01-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_player_playschedule_playerattendance_userplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='playschedule',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='playschedule',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='playschedule',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
